---
# task file for mysql
- name: "set the correct delegated_dbhost"
  set_fact:
    delegated_dbhost: "{{ zabbix_server_dbhostname if (zabbix_server_dbhostname != 'localhost') else inventory_hostname }}"

- name: "Set the host ip address for the database user"
  set_fact:
    zabbix_database_host: "{{ hostvars[inventory_hostname]['ansible_' + zabbix_server_database_interface]['ipv4']['address'] }}"

- block:
    - name: "mysql - create database"
      mysql_db:
        name: "{{ zabbix_server_dbname }}"
        encoding: "{{ zabbix_server_dbencoding }}"
        collation: "{{ zabbix_server_dbcollation }}"
        state: present
      when:
        - zabbix_database_creation
      register: zabbix_database_created
      delegate_to: "{{ delegated_dbhost }}"

    - name: "mysql | create database user"
      mysql_user:
        name: "{{ zabbix_server_dbuser }}"
        password: "{{ zabbix_server_dbpassword }}"
        host: "{{ zabbix_database_host }}"
        priv: "{{ zabbix_server_dbname }}.*:ALL"
        state: present
      when:
        - zabbix_database_creation
      delegate_to: "{{ delegated_dbhost }}"

    - name: "mysql - get the file for create.sql"
      shell: ls -1 {{ zabbix_datafiles_path }}/create.sq*
      changed_when: False
      when:
        - zabbix_database_sqlload
      register: ls_output_create

    - name: "mysql - check if we have done files"
      stat:
        path: /etc/zabbix/create.done
      register: done_file
      when:
        - zabbix_database_sqlload

    - name: "mysql - create database and import file"
      mysql_db:
        login_host: "{{ zabbix_server_mysql_login_host | default(omit) }}"
        login_user: "{{ zabbix_server_mysql_login_user | default(omit) }}"
        login_password: "{{ zabbix_server_mysql_login_password | default(omit) }}"
        login_port: "{{ zabbix_server_mysql_login_port | default(omit) }}"
        login_unix_socket: "{{ zabbix_server_mysql_login_unix_socket | default(omit) }}"
        name: "{{ zabbix_server_dbname }}"
        encoding: "{{ zabbix_server_dbencoding }}"
        collation: "{{ zabbix_server_dbcollation }}"
        state: import
        target: "{{ ls_output_create.stdout }}"
      register: zabbix_db_create
      when:
        - zabbix_database_created
        - zabbix_database_sqlload
        - not done_file.stat.exists
  run_once: true
  tags:
    - zabbix-server
    - database

- name: "mysql - create sql_done files"
  file:
    path: /etc/zabbix/create.done
    state: touch
  when:
    - zabbix_database_sqlload
    - zabbix_db_create.changed
  tags:
    - zabbix-server
    - database
