---

- import_role:
    name: ansible-role-apache

- name: "zabbix-web - set short version name"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
  tags:
    - always

- name: "zabbix-web - install apache vhost"
  template:
    src: apache_vhost.conf.j2
    dest: /etc/httpd/conf.d/zabbix.conf
    owner: "{{ zabbix_apache_user }}"
    group: "{{ zabbix_apache_group }}"
    mode: 0644
  when: zabbix_vhost
  notify:
    - restart apache
  tags:
    - zabbix-server

- name: "zabbix-web - create zabbix-web directory"
  file:
    path: /etc/zabbix/web
    owner: "{{ zabbix_apache_user }}"
    group: "{{ zabbix_apache_group }}"
    state: directory
    mode: 0755
  tags:
    - init
    - config

- name: "zabbix-web - configure zabbix-web"
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: "{{ zabbix_apache_user }}"
    group: "{{ zabbix_apache_group }}"
    mode: 0640
  notify:
    - restart apache
  tags:
    - init
    - config
