---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mysql-centos
    image: centos:7
    command: "/usr/sbin/init"
    env:
      container: docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/zabbix-server-mysql:/run
    networks:
      - name: private
      - name: replication
    groups:
      - galera
  - name: zabbix-server-centos
    image: centos:7
    command: "/usr/sbin/init"
    env:
      container: docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/zabbix-server-zabbix:/run
    networks:
      - name: private
      - name: replication
    groups:
      - zabbix
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      mysql:
        zabbix_server_database: mysql
        zabbix_server_database_long: mysql
        zabbix_server_dbport: 3306
scenario:
  name: default
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
verifier:
  name: testinfra
  lint:
    name: flake8
